// Mocks generated by Mockito 5.4.6 from annotations
// in train_with_joe/test/register_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:amplify_flutter/amplify_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:train_with_joe/services/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignInResult_0 extends _i1.SmartFake implements _i2.SignInResult {
  _FakeSignInResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthTokens_1 extends _i1.SmartFake implements _i3.AuthTokens {
  _FakeAuthTokens_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResult_2 extends _i1.SmartFake
    implements _i2.ResetPasswordResult {
  _FakeResetPasswordResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_3 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SignInResult> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i2.SignInResult>.value(
              _FakeSignInResult_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.SignInResult>);

  @override
  _i4.Future<_i3.AuthTokens> fetchTokens() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTokens, []),
            returnValue: _i4.Future<_i3.AuthTokens>.value(
              _FakeAuthTokens_1(this, Invocation.method(#fetchTokens, [])),
            ),
          )
          as _i4.Future<_i3.AuthTokens>);

  @override
  _i4.Future<_i2.SignInResult> confirmSignInWithNewPassword(
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSignInWithNewPassword, [newPassword]),
            returnValue: _i4.Future<_i2.SignInResult>.value(
              _FakeSignInResult_0(
                this,
                Invocation.method(#confirmSignInWithNewPassword, [newPassword]),
              ),
            ),
          )
          as _i4.Future<_i2.SignInResult>);

  @override
  _i4.Future<_i2.ResetPasswordResult> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<_i2.ResetPasswordResult>.value(
              _FakeResetPasswordResult_2(
                this,
                Invocation.method(#resetPassword, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.ResetPasswordResult>);

  @override
  _i4.Future<void> confirmResetPassword(
    String? email,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmResetPassword, [
              email,
              code,
              newPassword,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> register(String? email, String? password, {String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password], {#name: name}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> confirmSignUp(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSignUp, [email, code]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> resendSignUpCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendSignUpCode, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthUser> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.AuthUser>.value(
              _FakeAuthUser_3(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i4.Future<_i2.AuthUser>);

  @override
  _i4.Future<bool> isUserSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserSignedIn, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.AuthTokens> refreshTokens(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [refreshToken]),
            returnValue: _i4.Future<_i3.AuthTokens>.value(
              _FakeAuthTokens_1(
                this,
                Invocation.method(#refreshTokens, [refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthTokens>);
}
