// Mocks generated by Mockito 5.4.6 from annotations
// in train_with_joe/test/signin_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:amplify_flutter/amplify_flutter.dart' as _i2;
import 'package:flutter/widgets.dart' as _i6;
import 'package:go_router/src/configuration.dart' as _i5;
import 'package:go_router/src/delegate.dart' as _i7;
import 'package:go_router/src/information_provider.dart' as _i8;
import 'package:go_router/src/match.dart' as _i13;
import 'package:go_router/src/parser.dart' as _i9;
import 'package:go_router/src/router.dart' as _i11;
import 'package:go_router/src/state.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:train_with_joe/services/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignInResult_0 extends _i1.SmartFake implements _i2.SignInResult {
  _FakeSignInResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthTokens_1 extends _i1.SmartFake implements _i3.AuthTokens {
  _FakeAuthTokens_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResult_2 extends _i1.SmartFake
    implements _i2.ResetPasswordResult {
  _FakeResetPasswordResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_3 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterState_4 extends _i1.SmartFake implements _i4.GoRouterState {
  _FakeGoRouterState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_5 extends _i1.SmartFake
    implements _i5.RouteConfiguration {
  _FakeRouteConfiguration_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_6 extends _i1.SmartFake
    implements _i6.BackButtonDispatcher {
  _FakeBackButtonDispatcher_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_7 extends _i1.SmartFake
    implements _i7.GoRouterDelegate {
  _FakeGoRouterDelegate_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_8 extends _i1.SmartFake
    implements _i8.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_9 extends _i1.SmartFake
    implements _i9.GoRouteInformationParser {
  _FakeGoRouteInformationParser_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.SignInResult> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i10.Future<_i2.SignInResult>.value(
              _FakeSignInResult_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i10.Future<_i2.SignInResult>);

  @override
  _i10.Future<_i3.AuthTokens> fetchTokens() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTokens, []),
            returnValue: _i10.Future<_i3.AuthTokens>.value(
              _FakeAuthTokens_1(this, Invocation.method(#fetchTokens, [])),
            ),
          )
          as _i10.Future<_i3.AuthTokens>);

  @override
  _i10.Future<_i2.SignInResult> confirmSignInWithNewPassword(
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSignInWithNewPassword, [newPassword]),
            returnValue: _i10.Future<_i2.SignInResult>.value(
              _FakeSignInResult_0(
                this,
                Invocation.method(#confirmSignInWithNewPassword, [newPassword]),
              ),
            ),
          )
          as _i10.Future<_i2.SignInResult>);

  @override
  _i10.Future<_i2.ResetPasswordResult> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i10.Future<_i2.ResetPasswordResult>.value(
              _FakeResetPasswordResult_2(
                this,
                Invocation.method(#resetPassword, [email]),
              ),
            ),
          )
          as _i10.Future<_i2.ResetPasswordResult>);

  @override
  _i10.Future<void> confirmResetPassword(
    String? email,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmResetPassword, [
              email,
              code,
              newPassword,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> register(String? email, String? password, {String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password], {#name: name}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> confirmSignUp(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSignUp, [email, code]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> resendSignUpCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendSignUpCode, [email]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.AuthUser> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i10.Future<_i2.AuthUser>.value(
              _FakeAuthUser_3(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i10.Future<_i2.AuthUser>);

  @override
  _i10.Future<bool> isUserSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserSignedIn, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i3.AuthTokens> refreshTokens(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [refreshToken]),
            returnValue: _i10.Future<_i3.AuthTokens>.value(
              _FakeAuthTokens_1(
                this,
                Invocation.method(#refreshTokens, [refreshToken]),
              ),
            ),
          )
          as _i10.Future<_i3.AuthTokens>);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i11.GoRouter {
  MockGoRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_4(this, Invocation.getter(#state)),
          )
          as _i4.GoRouterState);

  @override
  _i5.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_5(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i5.RouteConfiguration);

  @override
  _i6.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_6(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i6.BackButtonDispatcher);

  @override
  _i7.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_7(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i7.GoRouterDelegate);

  @override
  _i8.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_8(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i8.GoRouteInformationProvider);

  @override
  _i9.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_9(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i9.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
          )
          as bool);

  @override
  set configuration(_i5.RouteConfiguration? value) => super.noSuchMethod(
    Invocation.setter(#configuration, value),
    returnValueForMissingStub: null,
  );

  @override
  set routerDelegate(_i7.GoRouterDelegate? value) => super.noSuchMethod(
    Invocation.setter(#routerDelegate, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationProvider(_i8.GoRouteInformationProvider? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, value),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationParser(_i9.GoRouteInformationParser? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, value),
        returnValueForMissingStub: null,
      );

  @override
  bool canPop() =>
      (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false)
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i13.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
