// Mocks generated by Mockito 5.4.6 from annotations
// in minimal_saas_template/test/subscription_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:in_app_purchase/in_app_purchase.dart' as _i5;
import 'package:minimal_saas_template/services/api_service.dart' as _i2;
import 'package:minimal_saas_template/services/payment_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> query(
    String? query, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [query], {#variables: variables}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> mutate(
    String? mutation, {
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mutate, [mutation], {#variables: variables}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i4.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onPurchaseUpdate(dynamic Function(Map<String, dynamic>)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onPurchaseUpdate, value),
        returnValueForMissingStub: null,
      );

  @override
  set onPurchaseError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onPurchaseError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> initialize({
    dynamic Function(Map<String, dynamic>)? onPurchaseUpdate,
    dynamic Function(String)? onPurchaseError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #onPurchaseUpdate: onPurchaseUpdate,
              #onPurchaseError: onPurchaseError,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.PaymentProvider detectPlatform() =>
      (super.noSuchMethod(
            Invocation.method(#detectPlatform, []),
            returnValue: _i4.PaymentProvider.stripe,
          )
          as _i4.PaymentProvider);

  @override
  _i3.Future<void> initializePayment() =>
      (super.noSuchMethod(
            Invocation.method(#initializePayment, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> processPayment(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [planId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> validateAppStoreReceipt(
    String? receiptData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateAppStoreReceipt, [receiptData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.PurchaseDetails>> getPendingPurchases() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingPurchases, []),
            returnValue: _i3.Future<List<_i5.PurchaseDetails>>.value(
              <_i5.PurchaseDetails>[],
            ),
          )
          as _i3.Future<List<_i5.PurchaseDetails>>);

  @override
  _i3.Future<Map<String, dynamic>> validatePlayStoreReceipt(
    String? purchaseToken,
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePlayStoreReceipt, [
              purchaseToken,
              productId,
            ]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> openStripeCheckout(String? checkoutUrl) =>
      (super.noSuchMethod(
            Invocation.method(#openStripeCheckout, [checkoutUrl]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> handleStripeCallback({
    required bool? success,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleStripeCallback, [], {
              #success: success,
              #sessionId: sessionId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
